const GAME_OF_LIFE_GRID = 'game-of-life/grid';

const SET_GRID = `${GAME_OF_LIFE_GRID}/SET_GRID`;
const PAUSE_GRID = `${GAME_OF_LIFE_GRID}/PAUSE_GRID`;
const PLAY_GRID = `${GAME_OF_LIFE_GRID}/PLAY_GRID`;
const GO_TO_NEXT_STEP = `${GAME_OF_LIFE_GRID}/GO_TO_NEXT_STEP`;
const ADD_GRID_COUNTER = `${GAME_OF_LIFE_GRID}/ADD_GRID_COUNTER`;

export {
  SET_GRID, PAUSE_GRID, PLAY_GRID, GO_TO_NEXT_STEP, ADD_GRID_COUNTER,
};
